### PR TITLE
feat: follow components and attributes to buefy@0.8.15

### PR DESCRIPTION
**Pull request by nogic1008**
ref: buefy/buefy#2363

## Works
- [x] [Button](https://buefy.org/documentation/button) (1558138)
- [x] [Carousel](https://buefy.org/documentation/carousel) (11ba25b)
- [x] [Collapse](https://buefy.org/documentation/collapse) (940238f)
- [x] [Dropdown](https://buefy.org/documentation/dropdown) (e0ee1fd)

- [x] [Autocomplete](https://buefy.org/documentation/autocomplete) (80a153f)
- [x] [Checkbox](https://buefy.org/documentation/checkbox) (eaf68d9)
- [x] [Clockpicker](https://buefy.org/documentation/clockpicker) (bb7144b)
- [x] [Datepicker](https://buefy.org/documentation/datepicker) (b471b5f)
- [x] [Datetimepicker](https://buefy.org/documentation/datetimepicker) (60fa090)
- [x] [Field](https://buefy.org/documentation/field) (a578dbf)
- [x] [Input](https://buefy.org/documentation/input) (57aa1af)
- [x] [Numberinput](https://buefy.org/documentation/numberinput) (f2296a0)
- [x] [Radio](https://buefy.org/documentation/radio) (c543b81)
- [x] [Rate](https://buefy.org/documentation/rate) (dd0fd4e)
- [x] [Select](https://buefy.org/documentation/select) (e45063d)
- [x] [Slider](https://buefy.org/documentation/slider) (b9da191)
- [x] [Switch](https://buefy.org/documentation/switch) (2ade978)
- [x] [Taginput](https://buefy.org/documentation/taginput) (6287068)
- [x] [Timepicker](https://buefy.org/documentation/timepicker) (ce9719c)
- [x] [Upload](https://buefy.org/documentation/upload) (no change)

- [x] [Icon](https://buefy.org/documentation/icon) (73d0be2)
- [x] [Loading](https://buefy.org/documentation/loading) (617d8e0)
- [x] [Menu](https://buefy.org/documentation/menu) (d048731)
- [x] [Message](https://buefy.org/documentation/message) (5783cb4)
- [x] [Modal](https://buefy.org/documentation/modal) (c0e6ab6)
- [x] [Navbar](https://buefy.org/documentation/navbar) (670fb64)
- [x] [Notification](https://buefy.org/documentation/notification) (4081e43)
- [x] [Pagination](https://buefy.org/documentation/pagination) (faeca06, 847b79c)
- [x] [Progress](https://buefy.org/documentation/progress) (a09f927)
- [x] [Sidebar](https://buefy.org/documentation/sidebar/) (#5)
- [x] [Steps](https://buefy.org/documentation/steps) (5e5fa7d)
- [x] [Table](https://buefy.org/documentation/table) (ed95ffa)
- [x] [Tabs](https://buefy.org/documentation/tabs) (3789391)
- [x] [Tag](https://buefy.org/documentation/tag) (ab4a355)
- [x] [Tooltip](https://buefy.org/documentation/tooltip) (09f932c)

- [x] remove `<b-panel>` (57f161d)

### CODE REVIEW

**Comment by nogic1008** [comment]
@jtommy Could you tell me what version of buefy this json supports?
I think it is from 0.7.1 to 0.7.4.

**Comment by jtommy** [comment]
What do you mean? The last version 0.8.15

**Comment by nogic1008** [comment]
Uh... I wanted to know diff from this repo's JSON and buefy@0.8.15 API surfaces.
I decided to check every component of the document, so I no longer need that information.

**Comment by jtommy** [comment]
Oh I'm sorry :(

**Comment by nogic1008** [comment]
What should I do with `<b-panel>` ? (keep or delete it)
it was deprecated since `0.5.3`, and removed in `0.7.0`.

**Comment by jtommy** [comment]
Remove it

**Comment by jtommy** [comment]
Awesome!!

**Pull request merged**
